language: node_js
node_js:
  - '12'
branches:
  only:
    - master
script:
  - npm run lint
  - npm run test
  - npm run build:prod
before_install:
  - npm i -g firebase-tools
deploy:
  provider: firebase
  token:
    secure: f2pXpGBq32Dwk5dMOkZS5ArioQvv9Opt2nlXbEje6FTW7N6Xs1QbzBpputquwvIr8dyYp2LuL4YahlMZwFeTmeHfTvbi8bv6dkrjp8JkZ5T4qWLxWSNjHl5M/QTz4vkU5eQPjh6AeL+lm2bkYhEWlEKlkoyL04EYF4Lnet62dXhkUF8FDYNkj7JT+gQTGoLcH7aYNUy53saOcD9u6n/kkxa8MJnOREi1uV/mr8bmwPv/50c6Z4ISYc7pIoVYgNNKM0AHYNKuGOSD58Y0pEJGmpbhxQvRm/fkj0j1d37kvDUL3zLFAno5Fmgv9uY83IbKvWeoRmWl1I+ketJ09yylQeQdKBWXiNGCabtwgr7fQp/wX1n/slXFkMKiy8o+ivqgq5ZTDv1sdhM1er4ijrQQXcHhd2DyvX5LNCTptQzoNUD1HMnyNa7YfElVJxJUArL6rghRDQBoj2qPlpLDE2vAEENTxHS3DEXXeXbslpKok3pJhOxwZcTIzBilmqKMX9aX3LIYTJ9kegeV7pX45utnhBTG/bIfNsc7m6A/GoEKo7QdApru7GpMBTGZDQPTCTfKTqb7UdN6qWi4NnJ+XqfFZkYhiueLAFrXBK5P6WP4JdD4Z67Er1jCK8oGGxmjGh6wSXlJK3UU1OQDMB8lbdjKCz7MxNTUGtu7KuU7shYSpRE=
  project: promotion-project-rs
  message: Success deploy
cache:
  directories:
    - node_modules
