language: node_js
node_js:
  - '12'
# env:
# - USER_EMAIL=$USER_EMAIL
# - USER_PASSWORD=$USER_PASSWORD
# - FIREBASE_API_KEY=$FIREBASE_API_KEY
# - FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
# - FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
# - FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
# - FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID
# - FIREBASE_APP_ID=$FIREBASE_APP_ID
branches:
  only:
    - master
before_script:
  - npm i -g firebase-tools
  - npm i -g http-server
script:
  - npm run lint
  - npm run test
  - npm run cy:ci
  - npm run build:prod
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
notifications:
  email:
    recipients:
      - strutynskyi.roman@gmail.com
    on_success: change
    on_failure: always
