language: node_js
node_js:
  - '12'
branches:
  only:
    - master
script:
  - npm run lint
  - npm run test
  - npm run build:prod
deploy:
  provider: firebase
  token:
    secure: YZVRxPXfo5JvH3waj1BE0Tl+qzpHkAQ9kPXyxoBH1cULD90s9OjQioInW5qJG33aDMiRmYo9eUsPM7LegvjAc/ZECOruWpZ0SPN1LJQjm8grQVLMg9cPZGnELcjyzIhfQxvXLcWj6osNHIh41ktML0W1zS4k3djp/wj4E/4rCiilb9Ls4iNHPMxmeAhPeWCa6OQqV8tsKha2VhgaNjIrZgpayRj81RiJjBJWZLYvGFrnM2ExYq/crb3t7t+EJeRxl9qXe747vJAI5NOA/LL4RZ+LHEQZi9z7dbmGWgxPyTGZFfEdzo9oAyiKZ3MFuYIG6aXit1FGC5xuDwK2V8fDSeHk1LBx/koq1lgmLwvyfcfzgx4ZeAC+lWL8fF63zr8Im0u+/VT6QsLiSxe2YfdNRzIiadrw0nd6deZklEwjrGgN0Tsph1PJB6ebErG77YUVnfShrUhhGo6p/Ib+jlZVAKlaE8Ql8ZzrE5s7VWJmVAp+Ce1renoXFpNHsviKy4JnR5u1az1w6I4tTJ/tNS//29C+1v6/n4zKxBaUj9rMtZzF9AyxpJHontQDX0Av1m0stROneGXgLAIAgfs4rPPRQ+cPBEXQmM0UxsjO7kAiPz3tx73kyDi7p5ADYLAxOlomk2SER6KCTaQ5ZowCrAfqR4YLIfv2XVypuYH/ghzilic=
  project: 'promotion-project-rs'
  message: 'Success deploy'
  clean_up: false
